name: Simple .NET Console App Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use .NET 9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      
      - name: Publish .NET project
        run: |
          dotnet publish -c Release -o ./dist ./HelloWorld/HelloWorld.csproj

      - name: Publish application as artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
          name: application

  deploy_to_dev:
    needs: build
    uses: ./reusable_deployment.yaml
    with:
      environment: Dev
      artifact: application
      application-name: HelloWorld

  deploy_to_test:
    needs: deploy_to_dev
    uses: ./reusable_deployment.yaml
    with:
      environment: Test
      artifact: application
      application-name: HelloWorld

  deploy_to_prod:
    needs: deploy_to_test
    uses: .reusable_deployment.yaml
    with:
      environment: Prod
      artifact: application
      application-name: HelloWorld