name: Simple .NET Console App Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use .NET 9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      
      - name: Publish .NET project
        run: |
          dotnet publish -c Release -o ./dist ./HelloWorld/HelloWorld.csproj

      - name: Publish application as artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
          name: app

  deploy_to_dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download application
        uses: actions/download-artifact@v4
        with:
          name: app
          path: ${{ github.workspace }}
        

      - name: Deploy to Dev
        run: |
          echo "Pre-deployment state:"
          ls -la

          mkdir dev
          cp ${{ github.workspace }}/app/* dev

          echo "Post-deployment state:"
          ls -la
          ls -la dev

          echo "Run the application"
          chmod +x dev/HelloWorld
          dev/HelloWorld