name: Reusable - Deploy to environment

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment to deploy to
        required: true
      runner:
        type: string
        description: Runner labels to use 
        default: "[ 'ubuntu-latest' ]"
      artifact:
        type: string
        description: Artifact to deploy
        default: app
      application-name:
        type: string
        description: Application to run
        required: true

jobs:
  deploy:
    runs-on: ${{ fromJson(inputs.runner) }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Download application
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact }}
          path: ${{ github.workspace }}/${{ inputs.artifact }}
      
      - name: Checkout code (so we can use composite action)
        uses: actions/checkout@v4
        with:
          path: actions
      
      - name: Deploy application
        uses: ./actions/.github/actions/DeployDotnet9
        with:
          environment: ${{ inputs.environment }}
          application-name: ${{ inputs.application-name }}