name: First Sample Actions Workflow

run-name: ${{ github.actor }} is learning GitHub Actions!

on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        type: string
        description: Who to greet

  issues:
    types:
      - opened

permissions:
  contents: read
  issues: write

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: echo "Hello from GitHub Actions!"
        name: Say hello

      - run: echo "Hello, ${{ inputs.who-to-greet || github.actor }}"
        name: Greet the person who triggered the workflow

      - run: |
          gh issue comment ${{ github.event.issue.number }} -b "Hello from GitHub Actions! Thanks for opening this issue!"
        name: React in issue
        if: ${{ github.event.issue }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    strategy:
      matrix:
        configuration: [ release, debug ]
        platform: [ x86, x64 ]
    steps:
      - run: echo "Hello from second job"
        name: Say hello again

      - run: echo "Running with platform ${{ matrix.platform }} and configuration ${{ matrix.configuration }}"
