name: First Sample Actions Workflow

run-name: ${{ github.actor }} is learning GitHub Actions!

on:
  workflow_dispatch:

  issues:
    types:
      - opened

permissions:
  contents: read
  issues: write

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: echo "Hello from GitHub Actions!"
        name: Say hello

      - run: echo "Hello, ${{ github.actor }}"
        name: Greet the person who triggered the workflow

      - run: |
          gh issue comment ${{ github.event.issue.number }} -b "Hello from GitHub Actions! Thanks for opening this issue!"
        name: React in issue
        if: ${{ github.event.issue }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
